# for REST API

version: '3'

services:
  server:
    image: s02210582/extra_2:rest_server
    ports:
      - "8080:8080"

  client:
    image: s02210582/extra_2:rest_client
    ports:
      - "8081:8081"
    volumes:
      - tasks:/app/data
    depends_on:
      - server

volumes:
  tasks:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/root/vol"